# Deploys my mysql server.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      # mysql container
      - name: mysql-db
        image: fayabobo/mysql:1.2
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD # Mind that the root has no right to connect on phpmyadmin.
          value: "1234"
        - name: MYSQL_USER # Without this user, it is not possible to connect on phpmyadmin
          value: jeweNaBobo
        - name: MYSQL_PASSWORD
          value: java