apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tomee-ingress
spec:
  tls:
  - secretName: my-secret
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: tomee-service-loadbalancer
          servicePort: 8080
