# Service which exposes my tomee
apiVersion: v1
kind: Service
metadata:
  name: tomee-service-loadbalancer
  annotations:
    cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
spec:
  type: LoadBalancer
  selector:
    app: tomee
  ports:
  - name: my-https-port
    port: 8443
    targetPort: 8443
  - name: my-http-port
    port: 8080
    targetPort: 8080
    # Once the server is launched on the local, impossible to login.
    # To know the credentials you have to follow the documentation and find these credentials in the file tomca-users.xml.
    # The command "kubectl exec -it podName /bin/sh" Will help you to go to the folder.
